# start with pane 1
set -g pane-base-index 1

# Enable mouse support
set -g mouse on

# Set default terminal mode to support 256 colors and true color
set -g default-terminal "tmux-256color"

# Enable true color support
set -as terminal-features ",xterm-256color:RGB"
set -as terminal-features ",alacritty:RGB"
set -as terminal-features ",kitty:RGB"

# Tokyo Night colors for Tmux
# Background: #1f2335
# Foreground: #c0caf5
# Active: #7aa2f7
# Orange: #ff9e64
# Comment/Gray: #565f89
# Inactive Background: #16161e
# Selection/Dark Blue: #3b4261

set -g status-justify left
set -g status-style "bg=#1f2335,fg=#7aa2f7"
set -g status-interval 2

# Border styles
set -g pane-border-style "fg=#3b4261"
set -g pane-active-border-style "fg=#7aa2f7"
set -g pane-border-lines "heavy"
set -g window-style 'bg=#16161e'
set -g window-active-style 'bg=terminal'

# Window status format
set-option -g status-position bottom
setw -g window-status-format " #[bg=#3b4261,fg=#c0caf5,noreverse]▓░ #W "
setw -g window-status-current-format " #[bg=#7aa2f7,fg=#1f2335,noreverse]▓░ #W "

# Left status (Session name)
set -g status-left-length 50
set -g status-left "#[fg=#1f2335,bg=#ff9e64,bold] #S #[fg=#ff9e64,bg=#1f2335]▓░"

# Right status (Date and Time)
set -g status-right-length 50
set -g status-right "#[fg=#565f89]▓░#[fg=#1f2335,bg=#565f89] %Y-%m-%d ▓░ %H:%M #[fg=#7aa2f7,bg=#565f89]▓░#[fg=#1f2335,bg=#7aa2f7,bold] #h "
